name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: ["Tests"]
    types: [completed]
    branches: [main]

jobs:
  coverage:
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install

    - name: Run tests with coverage
      run: |
        poetry run pytest --cov --cov-branch --cov-report=xml --cov-report=html -v
      shell: bash

    # - name: Upload coverage to Codecov (opcional)
    #   if: github.event_name == 'push'
    #   uses: codecov/codecov-action@v3
    #   with:
    #     file: ./coverage.xml
    #     flags: unittests
    #     name: codecov-umbrella
    #     fail_ci_if_error: false

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Store coverage reports
      uses: actions/upload-artifact@v4
      with:
        name: coverage-reports
        path: |
          coverage.xml
          htmlcov/
        retention-days: 30

    - name: Coverage comment (solo en PRs)
      if: github.event_name == 'pull_request'
      uses: py-cov-action/python-coverage-comment-action@v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  coverage-check:
    needs: [coverage]
    if: always()
    runs-on: ubuntu-latest

    steps:
    - name: Check coverage job status
      if: needs.coverage.result != 'success'
      run: |
        echo "Coverage job failed or was skipped"
        exit 1

    - name: Coverage completed successfully
      if: needs.coverage.result == 'success'
      run: echo "✅ Coverage analysis completed successfully"
